export LAB_LOCATION="italynorth"
export LAB_SUFFIX="5d62e4df"
export LAB_RG="rg-cea-ud02-${LAB_SUFFIX}"
export LAB_VNET="vnet-cea-ud02"
export LAB_SUBNET="snet-app"
export LAB_STORAGE="stceae7160ccc"
export LAB_DELETE_AFTER="$(date -v '+2d' +%F)"

export AUTO_SUFFIX="$(date +%s%N | sha256sum | cut -c1-8)"
export AUTO_LOCATION="$LAB_LOCATION"
export AUTO_RG="rg-cea-ud02-auto-${AUTO_SUFFIX}"
export AUTO_VNET="vnet-cea-auto"
export AUTO_SUBNET="snet-workload"
export AUTO_STORAGE="stceaauto${AUTO_SUFFIX}"
export AUTO_DELETE_AFTER="$(date -v '+2d' +%F)"